version: '2'

services:
  forumx:
    container_name: forumx
    image: 'forumx:latest'
    ports:
      - "8081:8080"
    build:
      context: src/main/docker
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/forumx
      - SPRING_DATASOURCE_USERNAME=forumx
      - SPRING_DATASOURCE_PASSWORD=forumx
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SERVER_PORT=8080
      - mailUserName=${mailUserName}
      - mailPassword=${mailPassword}
      - privateMail=${privateMail}
  db:
    container_name: forumx-pg
    image: 'postgres:13'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forumx
      - POSTGRES_PASSWORD=forumx
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock