version: '2'

services:
  forumx:
    image: 'forumx:latest'
    build:
      context: src/main/docker
    container_name: forumx
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: 'postgres:13'
    container_name: forumx-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forumx
      - POSTGRES_PASSWORD=forumx