version: '2'

services:
  forumx:
    image: 'forumx:latest'
    build:
      context: src/main/docker
    container_name: forumx
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/forumx
      - SPRING_DATASOURCE_USERNAME=forumx
      - SPRING_DATASOURCE_PASSWORD=forumx
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SERVER_PORT=8080

  db:
    image: 'postgres:13'
    container_name: forumx-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forumx
      - POSTGRES_PASSWORD=forumx